# Looping Over Datasets

In [1]:
for filename in ["./data/gapminder_gdp_asia.csv", "./data/gapminder_gdp_africa.csv"]:
    print(filename)

./data/gapminder_gdp_asia.csv
./data/gapminder_gdp_africa.csv


In [2]:
for filename in ["./data/gapminder_gdp_asia.csv", "./data/gapminder_gdp_africa.csv"]:
    file = open(filename)
    print(file.readline())
    file.close()

country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007

country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007



In [3]:
import glob

In [4]:
glob.glob("./data/*")

['./data\\gapminder_all.csv',
 './data\\gapminder_gdp_africa.csv',
 './data\\gapminder_gdp_americas.csv',
 './data\\gapminder_gdp_asia.csv',
 './data\\gapminder_gdp_europe.csv',
 './data\\gapminder_gdp_oceania.csv']

In [5]:
for filename in glob.glob("./data/*"):
    file = open(filename)
    print(file.readline())
    file.close()

"continent","country","gdpPercap_1952","gdpPercap_1957","gdpPercap_1962","gdpPercap_1967","gdpPercap_1972","gdpPercap_1977","gdpPercap_1982","gdpPercap_1987","gdpPercap_1992","gdpPercap_1997","gdpPercap_2002","gdpPercap_2007","lifeExp_1952","lifeExp_1957","lifeExp_1962","lifeExp_1967","lifeExp_1972","lifeExp_1977","lifeExp_1982","lifeExp_1987","lifeExp_1992","lifeExp_1997","lifeExp_2002","lifeExp_2007","pop_1952","pop_1957","pop_1962","pop_1967","pop_1972","pop_1977","pop_1982","pop_1987","pop_1992","pop_1997","pop_2002","pop_2007"

country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007

continent,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007

country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPe

In [6]:
glob.glob("./data/gapminder_gdp_a*")

['./data\\gapminder_gdp_africa.csv',
 './data\\gapminder_gdp_americas.csv',
 './data\\gapminder_gdp_asia.csv']

In [7]:
glob.glob("./data/*.csv")

['./data\\gapminder_all.csv',
 './data\\gapminder_gdp_africa.csv',
 './data\\gapminder_gdp_americas.csv',
 './data\\gapminder_gdp_asia.csv',
 './data\\gapminder_gdp_europe.csv',
 './data\\gapminder_gdp_oceania.csv']

In [8]:
glob.glob("./data/*gdp*")

['./data\\gapminder_gdp_africa.csv',
 './data\\gapminder_gdp_americas.csv',
 './data\\gapminder_gdp_asia.csv',
 './data\\gapminder_gdp_europe.csv',
 './data\\gapminder_gdp_oceania.csv']

use acculmulator pattern to collect items in column 3

combine above steps to calculate average

## Turn it into a Function

In [9]:
def average_for_a_column(col,data):
    collect = []
    for row in data:
        collect.append(float(row[col]))
    return sum(collect)/len(collect)

In [10]:
# Function to read CSV file
def read_csv_file(filepath):
    with open(filepath, 'r') as f:
        lines = f.readlines()
    
    # Clean and split each line
    lines = [line.strip().split(',') for line in lines]
    headers = lines[0]   # first row (column names)
    data = lines[1:]     # rest of the rows
    return headers, data



In [11]:
headers, data=read_csv_file("data/gapminder_gdp_americas.csv")

In [12]:
print(average_for_a_column(data=data, col = 4))

4901.5418704


## Use numpy

In [13]:
import numpy

In [14]:
numpy.loadtxt("data/gapminder_gdp_oceania.csv", skiprows = 1, usecols = range(1,13), delimiter = ",")

array([[10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
        18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
        30687.75473, 34435.36744],
       [10556.57566, 12247.39532, 13175.678  , 14463.91893, 16046.03728,
        16233.7177 , 17632.4104 , 19007.19129, 18363.32494, 21050.41377,
        23189.80135, 25185.00911]])

In [15]:
numpy.loadtxt("data/gapminder_gdp_oceania.csv", skiprows = 1, usecols = range(1,13), delimiter = ",", unpack = True)

array([[10039.59564, 10556.57566],
       [10949.64959, 12247.39532],
       [12217.22686, 13175.678  ],
       [14526.12465, 14463.91893],
       [16788.62948, 16046.03728],
       [18334.19751, 16233.7177 ],
       [19477.00928, 17632.4104 ],
       [21888.88903, 19007.19129],
       [23424.76683, 18363.32494],
       [26997.93657, 21050.41377],
       [30687.75473, 23189.80135],
       [34435.36744, 25185.00911]])

In [16]:
data = numpy.loadtxt("data/gapminder_gdp_oceania.csv", skiprows = 1, usecols = range(1,13), delimiter = ",")

In [17]:
data.shape

(2, 12)

In [23]:
print(average_for_a_column(data=data, col = 4))

16417.33338


In [27]:
data[:,4].mean()

np.float64(16417.33338)

In [28]:
data.mean()

np.float64(18621.609223333333)

In [29]:
data.max()

np.float64(34435.36744)

In [30]:
data.min()

np.float64(10039.59564)

In [31]:
len(data)

2

In [32]:
numpy.sqrt(data)

array([[100.19778261, 104.64057335, 110.53156499, 120.52437368,
        129.57094381, 135.40383122, 139.56005618, 147.94894062,
        153.05151692, 164.31048831, 175.17920747, 185.56768964],
       [102.74519775, 110.66795074, 114.78535621, 120.26603398,
        126.67295402, 127.4116074 , 132.78708672, 137.8665706 ,
        135.51134617, 145.08760722, 152.28197973, 158.69785477]])

In [34]:
data.dtype

dtype('float64')

In [35]:
import numpy as np

In [36]:
data**0.5

array([[100.19778261, 104.64057335, 110.53156499, 120.52437368,
        129.57094381, 135.40383122, 139.56005618, 147.94894062,
        153.05151692, 164.31048831, 175.17920747, 185.56768964],
       [102.74519775, 110.66795074, 114.78535621, 120.26603398,
        126.67295402, 127.4116074 , 132.78708672, 137.8665706 ,
        135.51134617, 145.08760722, 152.28197973, 158.69785477]])